# Generated by Django 5.2.7 on 2025-12-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desinkApp', '0003_profile_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
