# Generated by Django 5.2.7 on 2025-12-10 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desinkApp', '0008_alter_message_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
    ]
